def to_confededration(team: str):
    confederations = {
        "Scotland": "UEFA",
    "England": "UEFA",
    "Wales": "UEFA",
    "Northern Ireland": "UEFA",
    "United States": "CONCACAF",
    "Canada": "CONCACAF",
    "Uruguay": "CONMEBOL",
    "Argentina": "CONMEBOL",
    "Austria": "UEFA",
    "Hungary": "UEFA",
    "Czechoslovakia": "INVALID",
    "Belgium": "UEFA",
    "France": "UEFA",
    "Switzerland": "UEFA",
    "Guernsey": "INVALID",
    "Alderney": "INVALID",
    "Jersey": "INVALID",
    "Netherlands": "UEFA",
    "Germany": "UEFA",
    "Sweden": "UEFA",
    "Norway": "UEFA",
    "Italy": "UEFA",
    "Chile": "CONMEBOL",
    "Finland": "UEFA",
    "Luxembourg": "UEFA",
    "Catalonia": "INVALID",
    "Russia": "UEFA",
    "Denmark": "UEFA",
    "Philippines": "AFC",
    "China PR": "AFC",
    "Brazil": "CONMEBOL",
    "Basque Country": "INVALID",
    "Japan": "AFC",
    "Paraguay": "CONMEBOL",
    "Estonia": "UEFA",
    "Provence": "INVALID",
    "Costa Rica": "CONCACAF",
    "El Salvador": "CONCACAF",
    "Guatemala": "CONCACAF",
    "Yugoslavia": "INVALID",
    "Poland": "UEFA",
    "Spain": "UEFA",
    "Portugal": "UEFA",
    "Brittany": "INVALID",
    "Romania": "UEFA",
    "New Zealand": "OFC",
    "Australia": "AFC",
    "Latvia": "UEFA",
    "Galicia": "INVALID",
    "Central Spain": "INVALID",
        
    "Mexico": "CONCACAF",
    "Andalusia": "INVALID",
    "Asturias": "INVALID",
    "Lithuania": "UEFA",
    "Turkey": "UEFA",
    "Aruba": "CONCACAF",
    "Curaçao": "CONCACAF",
    "Bulgaria": "UEFA",
    "Egypt": "CAF",
    "Republic of Ireland": "UEFA",
    "South Africa": "CAF",
    "Haiti": "CONCACAF",
    "Jamaica": "CONCACAF",
    "Kenya": "CAF",
    "Uganda": "CAF",
    "Bolivia": "CONMEBOL",
    "Peru": "CONMEBOL",
    "Honduras": "CONCACAF",
    "Guyana": "CONCACAF",
    "Trinidad and Tobago": "CONCACAF",
    "Belarus": "UEFA",
    "Ukraine": "UEFA",
    "Barbados": "CONCACAF",
    "Nicaragua": "CONCACAF",
    "Greece": "UEFA",
    "Cuba": "CONCACAF",
    "Martinique": "CONCACAF",
    "Dominica": "CONCACAF",
    "Silesia": "INVALID",
    "Guadeloupe": "CONCACAF",
    "Israel": "UEFA",
    "Indonesia": "AFC",
    "Suriname": "CONCACAF",
    "French Guiana": "CONCACAF",
    "Saint Lucia": "CONCACAF",
    "Colombia": "CONMEBOL",
    "Panama": "CONCACAF",
    "Venezuela": "CONMEBOL",
    "Ecuador": "CONMEBOL",
    "Saint Kitts and Nevis": "CONCACAF",
    "Grenada": "CONCACAF",
    "India": "AFC",
    "Slovakia": "UEFA",
    "Manchukuo": "INVALID",
    "Croatia": "UEFA",
    "Lebanon": "AFC",
    "Puerto Rico": "CONCACAF",
    "Afghanistan": "AFC",
    "Iran": "AFC",
    "Mongolia": "AFC",
    "Tanzania": "CAF",
    "Zimbabwe": "CAF",
    "Zambia": "CAF",
    "Iceland": "UEFA",
    "Albania": "UEFA",
    "Montenegro": "UEFA",
    "Madagascar": "CAF",
    "Mauritius": "CAF",
    "Réunion": "INVALID",
    "Zanzibar": "INVALID",
    "Djibouti": "CAF",
    "Ethiopia": "CAF",
    "DR Congo": "CAF",
    "South Korea": "AFC",
    "Vietnam": "AFC",
    "Macau": "AFC",
    "Dominican Republic": "CONCACAF",
    "Cyprus": "UEFA",
    "Sierra Leone": "CAF",
    "Nigeria": "CAF",
    "Syria": "AFC",
    "Serbia": "UEFA",
    "Taiwan": "AFC",
    "Ghana": "CAF",
    "Burma": "INVALID",
    "New Caledonia": "OFC",
    "Vanuatu": "OFC",
    "Fiji": "OFC",
    
    
    "Myanmar": "AFC",
    "Pakistan": "AFC",
    "Sri Lanka": "AFC",
    "German DR": "INVALID",
    "Tahiti": "OFC",
    "Gambia": "CAF",
    "Hong Kong": "AFC",
    "Singapore": "AFC",
    "Malaysia": "AFC",
    "Guinea-Bissau": "CAF",
    "Saarland": "INVALID",
    "Burundi": "CAF",
    "Kernow": "INVALID",
    "Cambodia": "AFC",
    "Thailand": "AFC",
    "Vietnam Republic": "INVALID",
    "Kyrgyzstan": "AFC",
    "Moldova": "UEFA",
    "North Vietnam": "INVALID",
    "Togo": "CAF",
    "North Korea": "AFC",
    "Sudan": "CAF",
    "Malta": "UEFA",
    "Tunisia": "CAF",
    "Libya": "CAF",
    "Malawi": "CAF",
    "Morocco": "CAF",
    "Malaya": "INVALID",
    "Benin": "CAF",
    "Cape Verde": "CAF",
    "Cameroon": "CAF",
    "Central African Republic": "CAF",
    "Mali": "CAF",
    "Gabon": "CAF",
    "Burkina Faso": "CAF",
    "Ivory Coast": "CAF",
    "Congo": "CAF",
    "Iraq": "AFC",
    "Saint Vincent and the Grenadines": "CONCACAF",
    "Senegal": "CAF",
    "Laos": "AFC",
    "Mauritania": "CAF",
    "Liberia": "CAF",
    "Chad": "CAF",
    "Niger": "CAF",
    "Guinea": "CAF",
    "Algeria": "CAF",
    "Kuwait": "AFC",
    "Jordan": "AFC",
    "Papua New Guinea": "OFC",
    "Solomon Islands": "OFC",
    "Somalia": "CAF",
    "Saudi Arabia": "AFC",
    "Bermuda": "CONCACAF",
    "Palestine": "AFC",
    "Yemen": "AFC",
    "Bahrain": "AFC",
    "Oman": "AFC",
    "Wallis Islands and Futuna": "INVALID",
    "Corsica": "INVALID",
    "Western Australia": "INVALID",
    "Eswatini": "CAF",
    "Botswana": "CAF",
    "Qatar": "AFC",
    "Lesotho": "CAF",
    "Bahamas": "CONCACAF",
    "Brunei": "AFC",
    "Cook Islands": "OFC",
    "Yemen DPR": "INVALID",
    "United Arab Emirates": "AFC",
    "Faroe Islands": "UEFA",
    "Nepal": "AFC",
    
    
    "Antigua and Barbuda": "CONCACAF",
    "Bangladesh": "AFC",
    "Seychelles": "CAF",
    "Equatorial Guinea": "CAF",
    "Mozambique": "CAF",
    "Guam": "AFC",
    "Angola": "CAF",
    "São Tomé and Príncipe": "CAF",
    "Rwanda": "CAF",
    "Northern Cyprus": "INVALID",
    "Armenia": "UEFA",
    "Georgia": "UEFA",
    "Azerbaijan": "UEFA",
    "Kazakhstan": "UEFA",
    "Comoros": "CAF",
    "Maldives": "AFC",
    "Tonga": "OFC",
    "Kiribati": "OFC",
    "Tuvalu": "OFC",
    "Samoa": "OFC",
    "Greenland": "INVALID",
    "Liechtenstein": "UEFA",
    "Western Samoa": "INVALID",
    "Bhutan": "AFC",
    "South Yemen": "INVALID",
    "Niue": "OFC",
    "American Samoa": "OFC",
    "Belize": "CONCACAF",
    "Cayman Islands": "CONCACAF",
    "Anguilla": "CONCACAF",
    "British Virgin Islands": "CONCACAF",
    "Palau": "OFC",
    "Sint Maarten": "CONCACAF",
    "Namibia": "CAF",
    "Ynys Môn": "CONIFA",
    "Shetland": "CONIFA",
    "Åland Islands": "CONIFA",
    "Saint Martin": "CONCACAF",
    "San Marino": "UEFA",
    "Montserrat": "CONCACAF",
    "Slovenia": "UEFA",
    "Isle of Wight": "CONIFA",
    "Turkmenistan": "AFC",
    "Tajikistan": "AFC",
    "Uzbekistan": "AFC",
    "Eritrea": "CAF",
    "Czech Republic": "UEFA",
    "Gibraltar": "UEFA",
    "Isle of Man": "CONIFA",
    "North Macedonia": "UEFA",
    "Bosnia and Herzegovina": "UEFA",
    "Canary Islands": "INVALID",
    "Andorra": "UEFA",
    "Frøya": "CONIFA",
    "Hitra": "CONIFA",
    "United States Virgin Islands": "CONCACAF",
    "Northern Mariana Islands": "OFC",
    "Turks and Caicos Islands": "CONCACAF",
    "Micronesia": "OFC",
    "Gotland": "CONIFA",
    "Saare County": "CONIFA",
    "Rhodes": "CONIFA",
    "Monaco": "CONCACAF",
    "Tibet": "CONIFA",
    "Orkney": "CONIFA",
    "Falkland Islands": "CONMEBOL",
    "Mayotte": "CAF",
    "Vatican City": "INVALID",
    "Timor-Leste": "AFC",
    "Sark": "INVALID",
    "Sealand": "CONIFA",
    "Occitania": "CONIFA",
    "Chechnya": "CONIFA",
    "Ambazonia": "CONIFA",
    "Western Isles": "CONIFA",
    "Kosovo": "UEFA",
    "Republic of St. Pauli": "INVALID",
    "Găgăuzia": "CONIFA",
    "Crimea": "CONIFA",
    "Sápmi": "CONIFA",
    "Romani people": "CONIFA",
    "Menorca": "CONIFA",
    "Iraqi Kurdistan": "CONIFA",
    "Padania": "CONIFA",
    "Arameans Suryoye": "CONIFA",
    "Gozo": "CONIFA",
    "Two Sicilies": "CONIFA",
    "Saint Barthélemy": "CONCACAF",
    "Saint Pierre and Miquelon": "CONCACAF",
    "Bonaire": "CONCACAF",
    "Chagos Islands": "CONCACAF",
    "Raetia": "CONIFA",
    "Cilento": "INVALID",
    "Western Sahara": "INVALID",
    "Darfur": "CONIFA",
    "Tamil Eelam": "CONIFA",
    "South Sudan": "CAF",
    "Abkhazia": "CONIFA",
    "Artsakh": "CONIFA",
    "Madrid": "CONIFA",
    "Saugeais": "CONIFA",
    "Ellan Vannin": "CONIFA",
    "Somaliland": "CONIFA",
    "Franconia": "CONIFA",
    "South Ossetia": "CONIFA",
    "County of Nice": "CONIFA",
    "Seborga": "CONIFA",
    "Székely Land": "CONIFA",
    "Luhansk PR": "CONIFA"
    }
    
    try:
        return confederations[team]
    except KeyError:
        return "INVALID"